### ISSUE TITLE
Controlling chap with python/externally

### ISSUE THREAD

**Issue by juxeii** [vmware/chap#16]
### Is your feature request related to a problem? Please describe.

No problem.

### Describe the solution you'd like

How can I control chap programatically? For example, I can start it with python, but would like issue commands automatically.
What is the best approach for this, if any exists?

**Comment by timboddy** [comment]
Hi Juxeii,

Have you looked at https://docs.python.org/3/library/subprocess.html#   ?

It appears to support writing to the standard input of your child process and also reading the standard output and standard error of that child process.

**Comment by juxeii** [comment]
Hi,

I've found [pexpect](https://github.com/pexpect/pexpect), which does this job fairly well.
Thx.
